# Generated by Django 3.0 on 2024-12-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='SKILL',
        ),
    ]
