# Generated by Django 3.0 on 2025-03-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facilities',
        ),
    ]
