# Generated by Django 3.0 on 2025-03-18 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=400)),
                ('COLLEGE', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.College')),
            ],
        ),
    ]
