# Generated by Django 3.0 on 2024-12-03 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_college_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancy',
            new_name='Vaccancy',
        ),
        migrations.RenameField(
            model_name='vaccancy',
            old_name='start_datee',
            new_name='start_date',
        ),
    ]
