# Generated by Django 3.0 on 2024-12-03 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20241203_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='COLLEGE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.College'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vaccancy_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKILL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Skill')),
                ('VACANCY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Vaccancy')),
            ],
        ),
    ]
