# Generated by Django 3.0 on 2024-12-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20241203_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='COLLEGE',
        ),
    ]
