# Generated by Django 3.0 on 2025-01-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_facilities_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='COLLEGE',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.College'),
        ),
    ]
